In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
df = pd.read_csv("spam.csv",encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [4]:
df.shape

(5572, 5)

In [5]:
df = df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"])

In [6]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
df= df.drop_duplicates()

df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [8]:
df = df.dropna()
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [9]:
#rename cols name
df.columns= ["label","mg"]

In [10]:
df

     label                                                 mg
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [11]:
df["label"] = df["label"].str.strip().str.lower()
df["mg"] = df["mg"].str.strip()

In [12]:
df = df[df["label"].isin(["ham","spam"])]
#true value return karse khali aa

In [13]:
df

     label                                                 mg
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [14]:
df.columns

Index(['label', 'mg'], dtype='str')

In [15]:
df = df[df["mg"] != ""]
#remove empty mg

In [16]:
df.shape

(5169, 2)

In [17]:
print("\nLabel Counts:")
print(df["label"].value_counts())

Label Counts:
label
ham     4516
spam     653
Name: count, dtype: int64

In [18]:
#separate feature and target
X = df["mg"]
y = df["label"]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [20]:
print("\nTraining Messages:", len(X_train))
print("Testing Messages:", len(X_test))

Training Messages: 4135
Testing Messages: 1034

In [21]:
model = Pipeline([
    ("tfidf",TfidfVectorizer()),
    ("classifier",MultinomialNB())
])

In [22]:
model.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('classifier', MultinomialNB())])

In [23]:
y_pred = model.predict(X_test)

In [24]:
#evaluate model
acc = accuracy_score(y_test,y_pred)

In [25]:
print(acc)

0.9516441005802708

In [26]:
print("\nclassification report:")
cr = classification_report(y_test,y_pred)

classification report:

In [27]:
print("\n",cr)

               precision    recall  f1-score   support

         ham       0.95      1.00      0.97       903
        spam       1.00      0.62      0.76       131

    accuracy                           0.95      1034
   macro avg       0.97      0.81      0.87      1034
weighted avg       0.95      0.95      0.95      1034

In [28]:
cm = confusion_matrix(y_test,y_pred)
print("\n",cm)

 [[903   0]
 [ 50  81]]

In [29]:
my_messages = [
    "Congratulations! You won a free prize. Click here to claim.",
    "Hi, are we meeting tomorrow?",
    "URGENT! You have won cash. Call now to collect your reward.",
    "I will reach home in ten minutes.",
    "FREE entry in a weekly competition. Text WIN now!",
    "Please bring my notebook to college."
]

print("\n========== MY OWN MESSAGE TESTING ==========")

for message in my_messages:
    prediction = model.predict([message])[0]

    print("\nMessage:", message)

    if prediction == "spam":
        print("Prediction: SPAM")
    else:
        print("Prediction: NOT SPAM")

========== MY OWN MESSAGE TESTING ==========

Message: Congratulations! You won a free prize. Click here to claim.
Prediction: SPAM

Message: Hi, are we meeting tomorrow?
Prediction: NOT SPAM

Message: URGENT! You have won cash. Call now to collect your reward.
Prediction: SPAM

Message: I will reach home in ten minutes.
Prediction: NOT SPAM

Message: FREE entry in a weekly competition. Text WIN now!
Prediction: SPAM

Message: Please bring my notebook to college.
Prediction: NOT SPAM

In [30]:
baseline_pred = ["ham"] * len(y_test)
baseline_acc = accuracy_score(y_test,baseline_pred)

In [31]:
print(baseline_acc)

0.8733075435203095

In [32]:
import joblib
joblib.dump(model,"spamcollection.joblib")

['spamcollection.joblib']